backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'
public_folder: '/images'

collections:
  - name: 'about'
    label: 'About'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'src/content/about/index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image', required: false }
          - {
              label: 'Image alt text',
              name: 'imageAlt',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Image caption',
              name: 'imageCaption',
              widget: 'string',
              required: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
