backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'
public_folder: '/images'

collections:
  - name: 'about'
    label: 'About'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
